#!/usr/bin/env python3
"""
APT Logger Wrapper for mcp-kali-server
Proxies JSON-RPC stdio between MCP client and mcp_server.py,
intercepting tool calls and responses to produce structured session logs.

Usage (auto-generated by the Web UI):
    python3 apt_logger_wrapper.py [-- args for mcp_server.py...]
"""

import asyncio
import json
import os
import sys
import time
from datetime import datetime

from session_logger import SessionLogger, make_run_id


# ---------------------------------------------------------------------------
# Session setup
# ---------------------------------------------------------------------------

# If the web UI is driving this session, share its exact run ID.
# Otherwise generate a fresh ID per invocation.
if "MCP_CURRENT_RUN_ID" in os.environ:
    _run_id = os.environ["MCP_CURRENT_RUN_ID"]
else:
    _label = os.environ.get("MCP_RUN_ID", "apt")
    _run_id = make_run_id(_label)
_logger = SessionLogger(
    run_id=_run_id,
    metadata={
        "server_type": "apt",
        "model": os.environ.get("MCP_MODEL", "unknown"),
        "ollama_url": os.environ.get("MCP_OLLAMA_URL", "unknown"),
    }
)

# ---------------------------------------------------------------------------
# State tracking for matching requests → responses
# ---------------------------------------------------------------------------

_pending: dict[str, dict] = {}  # id → {method, params, t0}


def _handle_outgoing(msg: dict):
    """Track outgoing (client→server) tool-call requests."""
    method = msg.get("method", "")
    if method == "tools/call":
        req_id = str(msg.get("id", ""))
        params = msg.get("params", {})
        _pending[req_id] = {
            "tool": params.get("name", "unknown"),
            "args": params.get("arguments", {}),
            "t0": time.time(),
        }


def _handle_incoming(msg: dict):
    """Match incoming (server→client) tool-call responses and log them."""
    req_id = str(msg.get("id", ""))
    if req_id in _pending:
        pending = _pending.pop(req_id)
        duration_ms = int((time.time() - pending["t0"]) * 1000)

        result_text = ""
        error_text = ""
        exit_code = 0

        if "error" in msg:
            error_text = json.dumps(msg["error"])
            result_text = f"[ERROR] {error_text}"
            exit_code = -1
        else:
            content_list = msg.get("result", {}).get("content", [])
            result_text = "\n".join(
                c.get("text", "") for c in content_list if c.get("type") == "text"
            )

        _logger.log_tool_call(
            name=pending["tool"],
            args=pending["args"],
            result=result_text,
            duration_ms=duration_ms,
            exit_code=exit_code,
            stderr=error_text,
        )


# ---------------------------------------------------------------------------
# Async proxy loop
# ---------------------------------------------------------------------------

async def proxy(proc: asyncio.subprocess.Process):
    """Bidirectionally proxy stdin↔proc.stdin and proc.stdout→stdout."""

    async def stdin_to_proc():
        loop = asyncio.get_event_loop()
        stdin_reader = asyncio.StreamReader()
        await loop.connect_read_pipe(lambda: asyncio.StreamReaderProtocol(stdin_reader), sys.stdin.buffer)

        while True:
            line = await stdin_reader.readline()
            if not line:
                break
            proc.stdin.write(line)
            await proc.stdin.drain()

            # Attempt to parse and intercept
            try:
                msg = json.loads(line)
                _handle_outgoing(msg)
            except Exception:
                pass

        proc.stdin.close()

    async def proc_to_stdout():
        while True:
            line = await proc.stdout.readline()
            if not line:
                break
            sys.stdout.buffer.write(line)
            sys.stdout.buffer.flush()

            try:
                msg = json.loads(line)
                _handle_incoming(msg)
            except Exception:
                pass

    await asyncio.gather(
        stdin_to_proc(),
        proc_to_stdout(),
        return_exceptions=True,
    )


async def main():
    mcp_server_path = "/usr/share/mcp-kali-server/mcp_server.py"
    uv_bin = "/usr/local/bin/uv"

    cmd = [uv_bin, "run", "--offline", "--with", "mcp", "--with", "requests", mcp_server_path]

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=sys.stderr,  # let mcp_server.py's stderr pass through to terminal
    )

    try:
        await proxy(proc)
    finally:
        try:
            proc.terminate()
        except Exception:
            pass
        await proc.wait()
        _logger.finalize()


if __name__ == "__main__":
    asyncio.run(main())
