"""
tool_watcher.py — Background analysis agent for kali-mcp-webui.

Two operating modes (set in session_meta['watch_mode']):

  CONTINUOUS (default)
  ─────────────────────
  Watches transcript.md using watchdog (instant) or polls every `poll_interval`.
  Reads only NEW lines. Triggers an LLM call when ≥ `min_new_lines` arrive.
  Streams the LLM response (if supported by provider):
    - <note>...</note> tags → pushed live as `watcher_note_token` events
    - <json>...</json> tags → parsed after for tool suggestions
  Good for: real-time live commentary and zero-latency tool spotting.

  TIMER
  ──────
  Fires a full batch analysis at a fixed `timer_interval` (seconds).
  Reads the log span requested (all / last-N-lines / last-N-minutes).
  Produces a richer, summarizing analysis note + tool suggestions.
  Good for: periodic "what's happened" snapshots over a meaningful window.
"""

import json
import os
import queue
import re
import requests
import threading
import time
import uuid
from datetime import datetime, timedelta

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
    _WATCHDOG_AVAILABLE = True
except ImportError:
    _WATCHDOG_AVAILABLE = False


# ────────────────────────────────────────────────────────────────────────────
# Constants / defaults
# ────────────────────────────────────────────────────────────────────────────

_DEFAULT_POLL_INTERVAL = 10
_DEFAULT_TIMER_INTERVAL = 60
_DEFAULT_MIN_NEW_LINES = 3
_MAX_DIGEST_CHARS = 2000
_MAX_TIMER_CHARS = 4000

_SLUGIFY_RE = re.compile(r"[^a-z0-9]+")

_SCAFFOLD_HEADER = '''\
"""
Auto-suggested MCP tool scaffold — generated by ToolWatcher.
Review and adapt before adding to kali_tools.json or mcp_kali.py.
"""
import subprocess
import json
from mcp.server import Server
from mcp.types import Tool, TextContent

server = Server("mcp-{slug}")

@server.list_tools()
async def list_tools():
    return [
        Tool(
            name="{name}",
            description="{one_line}",
            inputSchema={{
                "type": "object",
                "properties": {{
                    "args": {{"type": "string", "description": "Arguments for the tool"}}
                }},
            }},
        )
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict):
    args = (arguments.get("args") or "").strip()
    result = subprocess.run(
        ["echo", f"{{name}}: {{args}}"],
        capture_output=True, text=True, timeout=60,
    )
    return [TextContent(type="text", text=result.stdout or result.stderr)]

if __name__ == "__main__":
    import asyncio
    from mcp.server.stdio import stdio_server
    async def main():
        async with stdio_server() as (r, w):
            await server.run(r, w, server.create_initialization_options())
    asyncio.run(main())
'''

# ────────────────────────────────────────────────────────────────────────────
# LLM prompts
# ────────────────────────────────────────────────────────────────────────────

_SYSTEM_PROMPT_CONTINUOUS = """\
You are a concise MCP tool designer watching a live penetration-testing agent session.
Identify ONE small, focused MCP tool that would reduce repeated manual effort or \
repetitive tool calls visible in the recent log excerpt.

Rules:
- Suggest at most ONE tool. Keep it scoped to a single command or tight 2-3 step sequence.
- Do NOT suggest tools that already exist in the available tool list.
- If there is no strong evidence of friction, emit an empty JSON tools list.

CRITICAL: You must output your response in TWO SECTIONS sequentially:
1. A <note>...</note> section containing a 1-2 sentence observation about what the agent is doing right now.
2. A <json>...</json> section containing valid JSON.

Format exactly like this:
<note>
The agent is repeatedly running nmap on port 80.
</note>
<json>
{
  "tools": [
    {
      "name": "<snake_case_tool_name>",
      "one_line": "<one sentence description>",
      "rationale": "<2-3 sentences>",
      "commands": "<shell command(s)>"
    }
  ]
}
</json>
"""

_SYSTEM_PROMPT_TIMER = """\
You are an expert MCP tooling analyst reviewing a penetration-testing agent session log.
Your job has two parts:

1. ANALYSIS NOTE — Write a concise 2-4 sentence summary of what the agent has been doing \
in the log window, highlighting any patterns or inefficiencies.

2. TOOL SUGGESTIONS — Identify up to 2 small MCP tools that would meaningfully \
reduce friction based on what you observed. Do NOT suggest existing tools.

Respond ONLY with valid JSON (no markdown fences, no extra text):
{
  "note": "<2-4 sentence analysis>",
  "tools": [
    {
      "name": "<snake_case_name>",
      "one_line": "<one sentence>",
      "rationale": "<2-3 sentences>",
      "commands": "<command(s)>"
    }
  ]
}
"""


# ────────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────────

def _slugify(name: str) -> str:
    return _SLUGIFY_RE.sub("_", name.lower()).strip("_")[:48]


def _call_llm(ollama_url: str, model: str, provider: str, api_key: str | None,
              ssl_verify: bool, system_prompt: str, user_content: str) -> dict | None:
    """Non-streaming LLM call (used by timer mode). Returns parsed JSON dict."""
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
        if provider == "litellm":
            headers["x-api-key"] = api_key
        elif provider == "claude":
            headers["x-api-key"] = api_key
            headers["anthropic-version"] = "2023-06-01"

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    try:
        if provider in ("litellm", "openai"):
            resp = requests.post(
                f"{ollama_url.rstrip('/')}/v1/chat/completions",
                headers=headers,
                json={"model": model, "messages": messages, "temperature": 0},
                timeout=60,
                verify=ssl_verify,
            )
            resp.raise_for_status()
            text = ((resp.json().get("choices") or [{}])[0].get("message") or {}).get("content", "")

        elif provider == "claude":
            resp = requests.post(
                f"{ollama_url.rstrip('/')}/v1/messages",
                headers=headers,
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": user_content}],
                    "system": system_prompt,
                    "max_tokens": 768,
                    "temperature": 0,
                },
                timeout=60,
                verify=ssl_verify,
            )
            resp.raise_for_status()
            text = "".join(
                b.get("text", "") for b in resp.json().get("content", [])
                if isinstance(b, dict) and b.get("type") == "text"
            )
        else:
            import ollama as _ollama
            client = _ollama.Client(host=ollama_url)
            resp = client.chat(model=model, messages=messages, options={"temperature": 0})
            text = (resp.get("message") or {}).get("content", "")

        text = text.strip()
        for fence in ("```json", "```"):
            if text.startswith(fence):
                text = text[len(fence):]
        text = text.strip(" `\n")
        return json.loads(text)

    except Exception as exc:
        print(f"[watcher/llm] Call failed: {exc}", flush=True)
        return None


def _stream_llm(ollama_url: str, model: str, provider: str, api_key: str | None,
                ssl_verify: bool, system_prompt: str, user_content: str):
    """
    Yields string chunks from the LLM response as they arrive.
    """
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
        if provider == "litellm":
            headers["x-api-key"] = api_key
        elif provider == "claude":
            headers["x-api-key"] = api_key
            headers["anthropic-version"] = "2023-06-01"

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    try:
        if provider in ("litellm", "openai"):
            resp = requests.post(
                f"{ollama_url.rstrip('/')}/v1/chat/completions",
                headers=headers,
                json={"model": model, "messages": messages, "temperature": 0, "stream": True},
                timeout=60,
                verify=ssl_verify,
                stream=True,
            )
            resp.raise_for_status()
            for line in resp.iter_lines():
                if line:
                    line = line.decode('utf-8')
                    if line.startswith("data: ") and line != "data: [DONE]":
                        try:
                            chunk = json.loads(line[6:])
                            text = chunk.get("choices", [{}])[0].get("delta", {}).get("content", "")
                            if text: yield text
                        except json.JSONDecodeError:
                            pass

        elif provider == "claude":
            resp = requests.post(
                f"{ollama_url.rstrip('/')}/v1/messages",
                headers=headers,
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": user_content}],
                    "system": system_prompt,
                    "max_tokens": 768,
                    "temperature": 0,
                    "stream": True,
                },
                timeout=60,
                verify=ssl_verify,
                stream=True,
            )
            resp.raise_for_status()
            for line in resp.iter_lines():
                if line:
                    line = line.decode('utf-8')
                    if line.startswith("data: "):
                        try:
                            chunk = json.loads(line[6:])
                            if chunk.get("type") == "content_block_delta" and chunk.get("delta", {}).get("type") == "text_delta":
                                text = chunk["delta"].get("text", "")
                                if text: yield text
                        except json.JSONDecodeError:
                            pass

        else:
            # Ollama direct
            import ollama as _ollama
            client = _ollama.Client(host=ollama_url)
            for chunk in client.chat(model=model, messages=messages, options={"temperature": 0}, stream=True):
                text = (chunk.get("message") or {}).get("content", "")
                if text: yield text

    except Exception as exc:
        print(f"[watcher/stream] Stream failed: {exc}", flush=True)


def _write_scaffold(suggested_tools_dir: str, slug: str, name: str, one_line: str) -> str:
    os.makedirs(suggested_tools_dir, exist_ok=True)
    path = os.path.join(suggested_tools_dir, f"{slug}.py")
    with open(path, "w") as f:
        f.write(_SCAFFOLD_HEADER.format(slug=slug, name=name, one_line=one_line))
    return path


def _read_transcript_lines(transcript_path: str) -> list[str]:
    if not os.path.isfile(transcript_path): return []
    with open(transcript_path, "r", errors="replace") as f:
        return f.readlines()


def _read_tool_call_snippets(tool_calls_dir: str, start_idx: int = 0, max_n: int = 8) -> tuple[list[str], int]:
    if not os.path.isdir(tool_calls_dir): return [], 0
    files = sorted(f for f in os.listdir(tool_calls_dir) if f.endswith(".json"))
    total = len(files)
    new_files = files[start_idx:]
    snippets = []
    for fname in new_files[-max_n:]:
        try:
            with open(os.path.join(tool_calls_dir, fname)) as f:
                rec = json.load(f)
            snippets.append(f"- tool={rec.get('tool')} args={str(rec.get('args', ''))[:120]}")
        except Exception:
            pass
    return snippets, total


def _push_suggestion(event_queue: queue.Queue, run_id: str,
                     suggested_tools_dir: str, slug: str, seen_slugs: set,
                     name: str, one_line: str, rationale: str, commands: str,
                     mode_label: str) -> bool:
    if slug in seen_slugs: return False
    seen_slugs.add(slug)

    scaffold_path = _write_scaffold(suggested_tools_dir, slug, name, one_line)
    try:
        with open(scaffold_path) as f: scaffold_code = f.read()
    except Exception:
        scaffold_code = ""

    try:
        event_queue.put_nowait({
            "type": "tool_suggestion",
            "timestamp": datetime.now().isoformat(),
            "run_id": run_id,
            "slug": slug,
            "name": name,
            "one_line": one_line,
            "rationale": rationale,
            "commands": commands,
            "scaffold_path": scaffold_path,
            "scaffold_code": scaffold_code,
            "source_mode": mode_label,
        })
        print(f"[watcher/{mode_label}] Suggested: {name}", flush=True)
        return True
    except queue.Full:
        return False


def _push_timer_note(event_queue: queue.Queue, run_id: str, note: str, span_label: str = ""):
    if not note or not note.strip(): return
    try:
        event_queue.put_nowait({
            "type": "watcher_analysis_note",
            "timestamp": datetime.now().isoformat(),
            "run_id": run_id,
            "note": note.strip(),
            "source_mode": "timer",
            "span_label": span_label,
        })
    except queue.Full:
        pass


# ────────────────────────────────────────────────────────────────────────────
# ToolWatcher Class
# ────────────────────────────────────────────────────────────────────────────

class ToolWatcher:
    def __init__(self):
        self._thread: threading.Thread | None = None
        self._stop_event = threading.Event()
        self.watchdog_available = _WATCHDOG_AVAILABLE
        self.watching_mode = ""  # 'timer', 'continuous-poll', or 'continuous-live'

    def start(self, run_id: str, session_meta: dict, event_queue: queue.Queue):
        self.stop()
        self._stop_event.clear()
        mode = session_meta.get("watch_mode", "continuous")
        
        target = self._run_continuous_stream if mode == "continuous" else self._run_timer
        
        self._thread = threading.Thread(
            target=target,
            args=(run_id, session_meta, event_queue),
            daemon=True,
            name=f"tool-watcher-{mode}",
        )
        self._thread.start()
        print(f"[watcher] Started in '{mode}' mode for run {run_id}", flush=True)

    def stop(self):
        if self._thread and self._thread.is_alive():
            self._stop_event.set()
            self._thread.join(timeout=5)
            print("[watcher] Stopped.", flush=True)
        self._thread = None
        self._stop_event.clear()
        self.watching_mode = ""

    def _paths(self, run_id: str) -> tuple[str, str, str, str]:
        base = os.path.dirname(os.path.abspath(__file__))
        run_dir = os.path.join(base, "runs", run_id)
        return (
            os.path.join(run_dir, "transcript.md"),
            os.path.join(run_dir, "tool_calls"),
            os.path.join(run_dir, "suggested_tools"),
            run_dir,
        )

    # ── Mode: Continuous Stream ──────────────────────────────────────────────

    def _run_continuous_stream(self, run_id: str, session_meta: dict, event_queue: queue.Queue):
        transcript_path, tool_calls_dir, suggested_tools_dir, run_dir = self._paths(run_id)
        ollama_url = session_meta.get("ollama_url", "http://localhost:11434")
        model = session_meta.get("model", "")
        provider = session_meta.get("llm_provider", "ollama_direct")
        api_key = session_meta.get("api_key") or None
        ssl_verify = session_meta.get("ssl_verify", True)
        
        poll_interval = int(session_meta.get("poll_interval", _DEFAULT_POLL_INTERVAL))
        min_new_lines = int(session_meta.get("min_new_lines", _DEFAULT_MIN_NEW_LINES))
        max_context_chars = int(session_meta.get("max_context_chars", _MAX_DIGEST_CHARS))

        seen_slugs: set[str] = set()
        
        # State for reading lines and rolling memory
        state = {'last_line_count': 0, 'last_tool_count': 0, 'analyzing': False, 'last_note': ''}

        # The actual analysis routine
        def _analyze_delta():
            if state['analyzing'] or self._stop_event.is_set() or not model: return
            state['analyzing'] = True
            
            try:
                all_lines = _read_transcript_lines(transcript_path)
                new_lines = all_lines[state['last_line_count']:]
                if len(new_lines) < min_new_lines:
                    state['analyzing'] = False
                    return
                state['last_line_count'] = len(all_lines)

                tool_snippets, tool_total = _read_tool_call_snippets(tool_calls_dir, start_idx=state['last_tool_count'])
                state['last_tool_count'] = tool_total

                digest = "".join(new_lines)
                if len(digest) > max_context_chars:
                    digest = digest[-max_context_chars:]

                user_content = ""
                if state['last_note']:
                    user_content += f"Previous analysis summary: {state['last_note']}\n\n"
                
                user_content += f"Recent transcript excerpt (new lines since last check):\n{digest}\n"
                if tool_snippets:
                    user_content += "\nRecent tool calls:\n" + "\n".join(tool_snippets) + "\n"

                # Start streaming SSE
                note_id = str(uuid.uuid4())
                try:
                    event_queue.put_nowait({
                        "type": "watcher_note_start",
                        "timestamp": datetime.now().isoformat(),
                        "run_id": run_id,
                        "note_id": note_id,
                        "source_mode": "continuous",
                    })
                except queue.Full:
                    pass

                full_text = ""
                in_note = False
                in_json = False
                
                # Stream process
                for chunk in _stream_llm(ollama_url, model, provider, api_key, ssl_verify, _SYSTEM_PROMPT_CONTINUOUS, user_content):
                    full_text += chunk
                    
                    # State machine for tags to know when to stream to UI
                    if "<note>" in full_text and "</note>" not in full_text:
                        if not in_note:
                            in_note = True
                            # Extract everything after <note> in chunk
                            idx = full_text.rfind("<note>") + 6
                            to_send = full_text[idx:]
                        else:
                            to_send = chunk
                            
                        # Avoid sending the closing tag if it arrives mid-chunk
                        if "</" in to_send: to_send = to_send.split("</")[0]
                        if to_send:
                            try: event_queue.put_nowait({"type": "watcher_note_token", "note_id": note_id, "token": to_send})
                            except queue.Full: pass
                
                # End of stream
                try: event_queue.put_nowait({"type": "watcher_note_complete", "note_id": note_id})
                except queue.Full: pass

                # Extract and store note for rolling memory
                note_match = re.search(r"<note>(.*?)(?:</note>|$)", full_text, re.DOTALL | re.IGNORECASE)
                if note_match:
                    state['last_note'] = note_match.group(1).strip()

                # Parse JSON tools
                json_match = re.search(r"<json>(.*?)(?:</json>|$)", full_text, re.DOTALL | re.IGNORECASE)
                if json_match:
                    try:
                        parsed = json.loads(json_match.group(1).strip())
                        for tool in (parsed.get("tools") or []):
                            name = str(tool.get("name", "")).strip()
                            one_line = str(tool.get("one_line", "")).strip()
                            if name and one_line:
                                _push_suggestion(
                                    event_queue, run_id, suggested_tools_dir,
                                    _slugify(name), seen_slugs, name, one_line,
                                    str(tool.get("rationale", "")),
                                    str(tool.get("commands", "")),
                                    "continuous",
                                )
                    except json.JSONDecodeError:
                        pass
                
            except Exception as exc:
                print(f"[watcher/continuous] Stream error: {exc}", flush=True)
            finally:
                state['analyzing'] = False


        # Setup watchdog or fallback to polling
        observer = None
        if self.watchdog_available:
            self.watching_mode = "continuous-live"
            
            class Handler(FileSystemEventHandler):
                def on_modified(self_handler, event):
                    if not event.is_directory and os.path.basename(event.src_path) == "transcript.md":
                        # Fire analyzer. It has an 'analyzing' lock so it won't concurrently stack.
                        threading.Thread(target=_analyze_delta, daemon=True).start()
            
            observer = Observer()
            observer.schedule(Handler(), path=run_dir, recursive=False)
            observer.start()
            
            # Still occasionally poll slowly to sweep anything missed
            while not self._stop_event.is_set():
                self._stop_event.wait(timeout=15)
                
            if observer:
                observer.stop()
                observer.join()
                
        else:
            self.watching_mode = "continuous-poll"
            while not self._stop_event.is_set():
                self._stop_event.wait(timeout=poll_interval)
                _analyze_delta()


    # ── Mode: Timer ────────────────────────────────────────────────────────

    def _run_timer(self, run_id: str, session_meta: dict, event_queue: queue.Queue):
        self.watching_mode = "timer"
        transcript_path, tool_calls_dir, suggested_tools_dir, _ = self._paths(run_id)
        ollama_url = session_meta.get("ollama_url", "http://localhost:11434")
        model = session_meta.get("model", "")
        provider = session_meta.get("llm_provider", "ollama_direct")
        api_key = session_meta.get("api_key") or None
        ssl_verify = session_meta.get("ssl_verify", True)
        
        timer_interval = int(session_meta.get("timer_interval", _DEFAULT_TIMER_INTERVAL))
        timer_span = session_meta.get("timer_span", "all")
        max_context_chars = int(session_meta.get("max_context_chars", _MAX_TIMER_CHARS))

        seen_slugs: set[str] = set()

        while not self._stop_event.is_set():
            self._stop_event.wait(timeout=timer_interval)
            if self._stop_event.is_set(): break
            if not model: continue

            try:
                all_lines = _read_transcript_lines(transcript_path)
                if not all_lines: continue

                span_label = "all log"
                lines_to_analyze = all_lines

                if timer_span.startswith("last_N_lines:"):
                    try:
                        n = int(timer_span.split(":")[1])
                        lines_to_analyze = all_lines[-n:]
                        span_label = f"last {n} lines"
                    except (IndexError, ValueError): pass

                elif timer_span.startswith("last_N_min:"):
                    try:
                        minutes = float(timer_span.split(":")[1])
                        cutoff = datetime.now() - timedelta(minutes=minutes)
                        filtered = _filter_lines_by_time(all_lines, cutoff)
                        if filtered:
                            lines_to_analyze = filtered
                            span_label = f"last {minutes:.0f} min"
                        else:
                            rate_guess = max(1, len(all_lines) // max(1, int(minutes * 6)))
                            lines_to_analyze = all_lines[-rate_guess:]
                            span_label = f"~last {minutes:.0f} min"
                    except (IndexError, ValueError): pass

                digest = "".join(lines_to_analyze)
                if len(digest) > max_context_chars:
                    head = digest[:400]
                    tail = digest[-(max_context_chars - 400):]
                    digest = head + "\n… [middle truncated] …\n" + tail

                tool_snippets, _ = _read_tool_call_snippets(tool_calls_dir, max_n=10)

                user_content = f"Log window: {span_label}\n\n{digest}\n"
                if tool_snippets:
                    user_content += "\nAll tool calls in window:\n" + "\n".join(tool_snippets) + "\n"

                result = _call_llm(ollama_url, model, provider, api_key, ssl_verify, _SYSTEM_PROMPT_TIMER, user_content)
                if not result: continue

                note = result.get("note", "")
                _push_timer_note(event_queue, run_id, note, span_label)

                for tool in (result.get("tools") or [])[:2]:
                    name = str(tool.get("name", "")).strip()
                    one_line = str(tool.get("one_line", "")).strip()
                    if name and one_line:
                        _push_suggestion(
                            event_queue, run_id, suggested_tools_dir,
                            _slugify(name), seen_slugs, name, one_line,
                            str(tool.get("rationale", "")),
                            str(tool.get("commands", "")),
                            "timer",
                        )

            except Exception as exc:
                print(f"[watcher/timer] Error: {exc}", flush=True)


def _filter_lines_by_time(lines: list[str], cutoff: datetime) -> list[str]:
    _TS_RE = re.compile(r'(\d{2}:\d{2}:\d{2})')
    today = datetime.now().date()
    result = []
    in_window = False
    found_any_ts = False
    for line in lines:
        m = _TS_RE.search(line)
        if m:
            found_any_ts = True
            try:
                t = datetime.strptime(m.group(1), "%H:%M:%S").replace(year=today.year, month=today.month, day=today.day)
                if t >= cutoff: in_window = True
            except ValueError: pass
        if in_window: result.append(line)
    return result if found_any_ts else []
